function page(area, titleDe, sentenceDe, itemsDe, titleEn, sentenceEn, itemsEn) {
  return {
    area,
    de: { title: titleDe, sentence: sentenceDe, items: itemsDe },
    en: { title: titleEn, sentence: sentenceEn, items: itemsEn },
  };
}

export const content = {
  home: {
    de: {
      title: "Universitätsmedizin Magdeburg",
      sentence: "Die Universitätsmedizin Magdeburg verbindet Krankenversorgung, Forschung und Lehre.",
    },
    en: {
      title: "University Medicine Magdeburg",
      sentence: "University Medicine Magdeburg combines patient care, research and teaching.",
    },
  },
  ui: {
    de: {
      searchLabel: "Suche",
      searchButton: "Suchen",
      onThisPage: "Auf dieser Seite",
      noResults: "Keine Treffer für",
      missing: "Diese Seite gibt es im Prototyp nicht",
      homeLink: "Zur Startseite",
      areaDirekt: "Direkt",
    },
    en: {
      searchLabel: "Search",
      searchButton: "Search",
      onThisPage: "On this page",
      noResults: "No results for",
      missing: "This page is not in the prototype",
      homeLink: "To the home page",
      areaDirekt: "Direct",
    },
  },
  areas: [
    {
      id: "behandlung",
      de: "Behandlung und Aufenthalt",
      en: "Treatment and stay",
      a: ["kliniken", "versorgungszentren", "institute", "ambulanzen", "aufenthalt", "zuweisende"],
      b: [
        { de: "Behandlung finden", en: "Find treatment", pages: ["kliniken", "versorgungszentren", "institute", "ambulanzen"] },
        { de: "Aufenthalt und Zuweisung", en: "Stay and referral", pages: ["aufenthalt", "zuweisende"] },
      ],
    },
    {
      id: "forschung",
      de: "Forschung und Innovation",
      en: "Research and innovation",
      a: ["schwerpunkte", "klinische-studien", "infrastruktur", "kooperationen", "nachwuchs"],
      b: [
        { de: "Themen", en: "Topics", pages: ["schwerpunkte", "klinische-studien"] },
        { de: "Zusammenarbeit", en: "Collaboration", pages: ["infrastruktur", "kooperationen", "nachwuchs"] },
      ],
    },
    {
      id: "studium",
      de: "Studium und Lehre",
      en: "Study and teaching",
      a: ["studieninteressierte", "studierende", "lehrende", "studiendekanat"],
      b: [
        { de: "Für Studieninteressierte", en: "For prospective students", pages: ["studienangebote", "bewerbung"] },
        { de: "Für Studierende", en: "For students", pages: ["moodle", "skillslab", "sp-programm"] },
        { de: "Für Lehrende", en: "For teachers", pages: ["lehrangebote", "weiterbildung"] },
        { de: "Anlaufstellen", en: "Contact points", pages: ["studiendekanat", "auslandsamt"] },
      ],
    },
    {
      id: "karriere",
      de: "Karriere und Ausbildung",
      en: "Career and training",
      a: ["stellenangebote", "berufungsverfahren", "ausbildung", "fortbildung", "benefits"],
      b: [
        { de: "Offene Stellen", en: "Open positions", pages: ["stellenangebote", "berufungsverfahren"] },
        { de: "Ausbildung und Arbeiten", en: "Training and working", pages: ["ausbildung", "fortbildung", "benefits"] },
      ],
    },
    {
      id: "ueber",
      de: "Über die UMMD",
      en: "About UMMD",
      a: ["wir", "leitung", "einrichtungen", "kultur", "presse"],
      b: [
        { de: "Porträt", en: "Portrait", pages: ["wir", "kultur", "presse"] },
        { de: "Leitung und Einrichtungen", en: "Leadership and institutions", pages: ["leitung", "einrichtungen"] },
      ],
    },
  ],
  hubs: {
    studieninteressierte: ["studienangebote", "bewerbung"],
    studierende: ["moodle", "skillslab", "sp-programm"],
    lehrende: ["lehrangebote", "weiterbildung"],
    studiendekanat: ["auslandsamt"],
  },
  synonyms: [
    { terms: ["notaufnahme", "notruf"], page: "notfall" },
    { terms: ["fachschaft", "fachschaftsrat"], page: "moodle" },
    { terms: ["pj", "praktisches jahr"], page: "moodle" },
    { terms: ["international", "ausland"], page: "bewerbung" },
    { terms: ["anfahrt", "parken", "adresse"], page: "kontakt" },
    { terms: ["zuweisung", "einweisung"], page: "zuweisende" },
    { terms: ["jobs", "stellen"], page: "stellenangebote" },
  ],
  pageOrder: [
    "notfall", "kontakt",
    "kliniken", "versorgungszentren", "institute", "ambulanzen", "aufenthalt", "zuweisende",
    "schwerpunkte", "klinische-studien", "infrastruktur", "kooperationen", "nachwuchs",
    "studieninteressierte", "studierende", "lehrende", "studiendekanat",
    "studienangebote", "bewerbung", "moodle", "skillslab", "sp-programm",
    "lehrangebote", "weiterbildung", "auslandsamt",
    "stellenangebote", "berufungsverfahren", "ausbildung", "fortbildung", "benefits",
    "wir", "leitung", "einrichtungen", "kultur", "presse",
  ],
  pages: {
    notfall: page("direkt", "Notfall", "Hilfe bei einem medizinischen Notfall auf dem Campus.", ["Notaufnahme", "Notruf", "Weg zur Notaufnahme"], "Emergency", "Help in a medical emergency on campus.", ["Emergency department", "Emergency number", "Way to the emergency department"]),
    kontakt: page("direkt", "Kontakt und Anfahrt", "So erreichen Sie die UMMD.", ["Adresse", "Anfahrt", "Parken", "Kontakt"], "Contact and directions", "How to reach UMMD.", ["Address", "Directions", "Parking", "Contact"]),
    kliniken: page("behandlung", "Kliniken", "Die Kliniken der UMMD im Überblick.", ["Klinikübersicht", "Ansprechpartner", "Sprechstunden"], "Clinics", "The UMMD clinics at a glance.", ["Clinic overview", "Contacts", "Consultation hours"]),
    versorgungszentren: page("behandlung", "Medizinische Versorgungszentren", "Versorgung außerhalb der Kliniken.", ["Standorte der Zentren", "Angebote", "Kontakt"], "Medical care centers", "Care outside the clinics.", ["Center locations", "Services", "Contact"]),
    institute: page("behandlung", "Institute", "Die Institute der Medizinischen Fakultät.", ["Institutsübersicht", "Forschung an den Instituten", "Kontakt"], "Institutes", "The institutes of the Medical Faculty.", ["Institute overview", "Research at the institutes", "Contact"]),
    ambulanzen: page("behandlung", "Ambulanzen", "Ambulante Behandlung an der UMMD.", ["Ambulanzübersicht", "Sprechstunden", "Anmeldung"], "Outpatient clinics", "Outpatient care at UMMD.", ["Outpatient clinic overview", "Consultation hours", "Registration"]),
    aufenthalt: page("behandlung", "Aufenthalt und Besuch", "Informationen für den Aufenthalt und für Besuche.", ["Besuchszeiten", "Übernachtung", "Service vor Ort"], "Stay and visit", "Information for a stay and for visits.", ["Visiting hours", "Overnight stay", "On-site services"]),
    zuweisende: page("behandlung", "Für Zuweisende", "Zugang für zuweisende Ärztinnen und Ärzte.", ["Zuweisung", "Einweisung", "Kontakt"], "For referring physicians", "Access for referring physicians.", ["Referral", "Admission", "Contact"]),
    schwerpunkte: page("forschung", "Forschungsschwerpunkte", "Die wissenschaftlichen Schwerpunkte der UMMD.", ["Schwerpunkte", "Suche Einrichtung", "beteiligte Kliniken"], "Research focus areas", "The scientific focus areas of UMMD.", ["Focus areas", "Find a facility", "Participating clinics"]),
    "klinische-studien": page("forschung", "Klinische Studien", "Studien, an denen die UMMD beteiligt ist.", ["Laufende Studien", "Teilnahme", "Kontakt"], "Clinical studies", "Studies that UMMD takes part in.", ["Current studies", "Participation", "Contact"]),
    infrastruktur: page("forschung", "Forschungsinfrastruktur", "Geräte und Einrichtungen für die Forschung.", ["Zentrale Forschungsplattformen", "Großgeräte", "Nutzung"], "Research infrastructure", "Equipment and facilities for research.", ["Central research platforms", "Large equipment", "Use"]),
    kooperationen: page("forschung", "Kooperationen", "Partner in Forschung und Versorgung.", ["Verbünde", "Partner", "Ansprechpartner"], "Cooperations", "Partners in research and care.", ["Networks", "Partners", "Contacts"]),
    nachwuchs: page("forschung", "Nachwuchsförderung", "Wege in die wissenschaftliche Karriere.", ["Promotion", "Programme", "Beratung"], "Early career support", "Paths into a scientific career.", ["Doctorate", "Programs", "Advice"]),
    studieninteressierte: page("studium", "Für Studieninteressierte", "Einstieg für Menschen, die an der UMMD studieren wollen.", ["Studienangebote", "Bewerbung"], "For prospective students", "Starting point for people who want to study at UMMD.", ["Study programs", "Application"]),
    studierende: page("studium", "Für Studierende", "Einstieg für eingeschriebene Studierende.", ["Moodle", "Skillslab", "SP-Programm", "PJ", "Fachschaftsrat"], "For students", "Starting point for enrolled students.", ["Moodle", "Skillslab", "SP program", "PJ", "Student council"]),
    lehrende: page("studium", "Für Lehrende", "Einstieg für Lehrende der UMMD.", ["Lehrangebote", "Weiterbildung"], "For teachers", "Starting point for teachers at UMMD.", ["Teaching offers", "Continuing education"]),
    studiendekanat: page("studium", "Studiendekanat", "Anlaufstelle für Studium und Lehre.", ["Ansprechpartner", "Akademisches Auslandsamt"], "Dean of Studies office", "Contact point for study and teaching.", ["Contacts", "International Office"]),
    studienangebote: page("studium", "Studienangebote", "Welche Studiengänge die UMMD anbietet.", ["Studiengänge", "Abschlüsse", "Voraussetzungen"], "Study programs", "Which degree programs UMMD offers.", ["Degree programs", "Degrees", "Requirements"]),
    bewerbung: page("studium", "Bewerbung", "So bewerben Sie sich um einen Studienplatz.", ["Fristen", "Voraussetzungen", "Bewerbung international"], "Application", "How to apply for a place to study.", ["Deadlines", "Requirements", "International application"]),
    moodle: page("studium", "Moodle", "Die Lernplattform für Studierende.", ["Zugang", "Kurse", "PJ", "Fachschaftsrat"], "Moodle", "The learning platform for students.", ["Access", "Courses", "PJ", "Student council"]),
    skillslab: page("studium", "Skillslab", "Üben praktischer Fertigkeiten.", ["Kurse", "Räume", "PJ", "Fachschaftsrat"], "Skillslab", "Practice for clinical skills.", ["Courses", "Rooms", "PJ", "Student council"]),
    "sp-programm": page("studium", "SP-Programm", "Das Studienprogramm SP.", ["Aufbau", "Anmeldung", "PJ", "Fachschaftsrat"], "SP program", "The SP study program.", ["Structure", "Registration", "PJ", "Student council"]),
    lehrangebote: page("studium", "Lehrangebote", "Lehre an der UMMD für Dozierende.", ["Lehrveranstaltungen", "Materialien", "Ansprechpartner"], "Teaching offers", "Teaching at UMMD for lecturers.", ["Courses", "Materials", "Contacts"]),
    weiterbildung: page("studium", "Weiterbildung", "Weiterbildung für Lehrende.", ["Medizindidaktik", "Kurse", "Anmeldung"], "Continuing education", "Continuing education for teachers.", ["Medical didactics", "Courses", "Registration"]),
    auslandsamt: page("studium", "Akademisches Auslandsamt", "Studium mit internationalem Bezug.", ["Auslandsaufenthalt", "Studierende aus dem Ausland", "Bewerbung international"], "International Office", "Study with an international dimension.", ["Stay abroad", "Students from abroad", "International application"]),
    stellenangebote: page("karriere", "Stellenangebote", "Offene Stellen an der UMMD.", ["Aktuelle Stellen", "Bewerbung auf eine Stelle", "Kontakt"], "Job openings", "Open positions at UMMD.", ["Current positions", "Apply for a position", "Contact"]),
    berufungsverfahren: page("karriere", "Berufungsverfahren", "Verfahren für Professuren.", ["Laufende Verfahren", "Ablauf", "Kontakt"], "Appointment procedures", "Procedures for professorships.", ["Current procedures", "Process", "Contact"]),
    ausbildung: page("karriere", "Ausbildung", "Ausbildung an der UMMD.", ["Berufe", "freie Plätze", "Bewerbung"], "Vocational training", "Vocational training at UMMD.", ["Occupations", "Open places", "Application"]),
    fortbildung: page("karriere", "Fort- und Weiterbildung", "Fortbildung für Beschäftigte.", ["Programm", "Anmeldung", "Zertifikate"], "Staff training", "Continuing education for staff.", ["Program", "Registration", "Certificates"]),
    benefits: page("karriere", "Benefits", "Was die UMMD als Arbeitgeberin bietet.", ["Arbeitsbedingungen", "Familie", "Entwicklung"], "Benefits", "What UMMD offers as an employer.", ["Working conditions", "Family", "Development"]),
    wir: page("ueber", "Wer wir sind", "Auftrag und Aufbau der UMMD.", ["Krankenversorgung", "Forschung", "Lehre", "Standorte"], "Who we are", "Mission and structure of UMMD.", ["Patient care", "Research", "Teaching", "Sites"]),
    leitung: page("ueber", "Leitungsvorstand", "Die Leitung der UMMD.", ["Mitglieder", "Aufgaben", "Kontakt"], "Executive board", "The leadership of UMMD.", ["Members", "Responsibilities", "Contact"]),
    einrichtungen: page("ueber", "Einrichtungen", "Einrichtungen unter dem Dach der UMMD.", ["Fakultät", "Klinikum", "weitere Einrichtungen"], "Institutions", "Institutions under the UMMD umbrella.", ["Faculty", "University hospital", "Other institutions"]),
    kultur: page("ueber", "Kultur und Werte", "Wofür die UMMD steht.", ["Leitbild", "Zusammenarbeit", "Qualität und Verantwortung"], "Culture and values", "What UMMD stands for.", ["Mission statement", "Collaboration", "Quality and responsibility"]),
    presse: page("ueber", "Presse und Aktuelles", "Neuigkeiten und Pressekontakt.", ["Meldungen", "Pressekontakt", "Bildmaterial"], "Press and news", "News and press contact.", ["News", "Press contact", "Images"]),
  },
};
